### ISSUE TITLE
double and float types in JSON

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#155]
ODPI-C version: 4.1.0
Oracle client version: 21.1

According to [this document](https://docs.oracle.com/en/database/oracle/oracle-database/21/adjsn/json-in-oracle-database.html#GUID-E075CA14-DC89-4F9D-AD6F-C351F774575A), Oracle Database extends the set of standard JSON-language types to include `double` and `float`. However ODPI-C supports it partially. Is it on purpose?

JSON &rarr; Native
* [`DPI_JZNVAL_DOUBLE` &rarr; `DPI_ORACLE_TYPE_NUMBER` and `DPI_NATIVE_TYPE_DOUBLE`](https://github.com/oracle/odpi/blob/v4.1.0/src/dpiJson.c#L268-L271)
* [`DPI_JZNVAL_FLOAT` &rarr; `DPI_ORACLE_TYPE_NUMBER` and `DPI_NATIVE_TYPE_DOUBLE`](https://github.com/oracle/odpi/blob/v4.1.0/src/dpiJson.c#L263-L266)

Native &rarr; JSON
* [`DPI_ORACLE_TYPE_NUMBER` and `DPI_NATIVE_TYPE_DOUBLE` &rarr; `DPI_JZNVAL_ORA_NUMBER`](https://github.com/oracle/odpi/blob/v4.1.0/src/dpiJson.c#L457-L474)
* `DPI_ORACLE_TYPE_NATIVE_DOUBLE` and `DPI_NATIVE_TYPE_DOUBLE` &rarr; ERROR
* `DPI_ORACLE_TYPE_NATIVE_FLOAT` and `DPI_NATIVE_TYPE_FLOAT` &rarr; ERROR

When a JSON value is got from DB and written back, `double` and `float` in JSON are converted to Oracle number.
(Well, this is a guess. I have no user accounts of Oracle 21c.)

**Comment by anthony-tuininga** [comment]
You're correct. The values for double and float are converted to Oracle Number -- which has a different range of supported values. I think the reason for doing so was to make driver development simpler -- since they likely deal with Oracle Number for regular columns and rarely (if ever) deal with native doubles and floats. Internally Oracle is capable of storing Oracle Number inside JSON values as well -- and preserving the distinction might be more complex than most people are willing to deal with. I'll discuss with @cjbj and get back to you further on this matter. If you have further comments/suggestions I'd be happy to hear them!

**Comment by cjbj** [comment]
@kubo do we have a current email address for you?  Can you email me if you have a new one?

**Comment by kubo** [comment]
@cjbj My email address has not been changed for about twenty years.

**Comment by cjbj** [comment]
@kubo I wonder if mail from oracle.com isn't reaching you?  I've just sent you a test email.

**Comment by cjbj** [comment]
@anthony-tuininga you gave yourself an action item on this.

**Comment by anthony-tuininga** [comment]
Apologies for the delay! I took a look and realised that there was no way to pass in native_double/native_float values directly. That has been corrected. Take a look and let me know if that resolves your issue. Thanks!

**Comment by kubo** [comment]
@anthony-tuininga 
Thanks.
I forgot to close this.
