### ISSUE TITLE
The last argument of dpiConn_newSubscription must be `uint64_t *`.

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#28]
I found a bug when I made a [test code](https://gist.github.com/kubo/394af98c4c541b2e069467a97f0aaec9) about #27.
`dpiConn_newSubscription` overwrites additional four bytes after the address passed as the last argument.

Look at https://gist.github.com/kubo/394af98c4c541b2e069467a97f0aaec9#file-subscr-test-c-L51-L55.
If the last argument of `dpiConn_newSubscription` is `uint32_t *`, `subscrId.next4byte` must be 0xdeadbeaf at line 53. However it became 0x00000000.
I guess that the type is `uint64_t *` so the next four bytes were overwritten with 0x00000000.

**Comment by anthony-tuininga** [comment]
Thanks, @kubo. I'll take a look.

**Comment by anthony-tuininga** [comment]
So you are correct. The last parameter of dpiConn_newSubscription() is supposed to be uint64_t *. I have corrected that, but in consultation with my colleagues this parameter is also deprecated (and NULL can be passed to it now) and will be removed in version 2.1. It is not documented in OCI and was never intended to be used. It was originally introduced by a patch to cx_Oracle back in 2012 provided by someone -- not sure how they figured it out back then since there wasn't any documentation!
