### ISSUE TITLE
Not able to get and print all the row values fetched using dpiStmt_fetchRows

### ISSUE THREAD

**Issue by SKAHIRON** [oracle/odpi#70]
Hi, I am currently developing an application using latest ODPIC where I am using dpiStmt_fetchRows function to fetch multiple rows at a time. But I am not able to get all the fetched values using dpiStmt_getQueryValue. Need immediate help to know if dpiStmt_getQueryValue is the correct function to be used here. Also please help me out how to get all the values fetched using dpiStmt_fetchRows.
Please find below the code snippet I have used in the code:
if (dpiStmt_fetchRows(stmt, maxRows, &bufferRowIndex, &numRowsFetched,&moreRows) == DPI_SUCCESS)
{
..........
..........
if (dpiStmt_getQueryValue(stmt,1,&nativeTypeNum, &intColFetchValue) == DPI_SUCCESS)
{
printf("Col Value for Row %d : %s\n", nCount, intColFetchValue->value.asBytes.ptr);
}
}

I am developing the application in Linux platform.
Any kind of help in this regard would be greatly appreciated. Thank you.

**Comment by anthony-tuininga** [comment]
If you want to use dpiStmt_getQueryValue() you would generally pair that with a call to dpiStmt_fetch() instead. That indicates if a row is available and provides a buffer row index (which you can ignore if you intend to use dpiStmt_getQueryValue() instead of reading the values directly from the variable data buffers). You can see what this looks like in the [sample](https://github.com/oracle/odpi/blob/master/samples/TestFetch.c).

Note that dpiStmt_fetch() will make use of array fetch internally so you don't have to worry about performing excessive round-trips to the database. The method dpiStmt_fetchRows() is intended for when you need to control when new rows are fetched from the database. But if you use that method you have to access the variable data buffers yourself directly. You can see how that is done in the [cx_Oracle driver](https://github.com/oracle/python-cx_Oracle) if that is of interest.

**Comment by SKAHIRON** [comment]
Thanks a lot Anthony for your quick and valuable response. I just need to understand one more point. Actually I want to fetch bulk rows from a table at a time and pass the fetched rows to another function for printing. This is not possible using dpiStmt_fetch() because this function fetches one row at a time. Then I researched and found dpiStmt_fetchRows(). Now I want to know, does this function (dpiStmt_fetchRows()) returns multiple rows at a time or simply returns count of rows? Because I saw this functions takes (maxrows) as one of its parameters. If this functions returns multiple rows then how to get the values from the fetched rows and print them. Function dpiStmt_getQueryValue() can only used for dpiStmt_fetch() but not for multiple rows. I have gone through the  codes in (cx_Oracle driver project) as you suggested but there I saw dpiStmt_fetchRows() has been used but fetched rows are not stored or handled anywhere. Would you please respond once again. And also would you please suggest, between dpiStmt_fetch() and dpiStmt_fetchRows() which one is better in terms of performance. Thanks once again.

**Comment by SKAHIRON** [comment]
Thanks again Anthony. One more point I need to understand, after that I would be good. Suppose I need to fetch one million records from a table. Now if I want 1000 records to be fetched in parallel, how to use dpiStmt_fetch() function for that. For fetching 1000 records at a time I need to first set the size of the cache to 1000. After that will I be able to do some steps so that it fetches first 1000 records and next 1000 records simultaneously. If so the how to do that please suggest. Thank you.

**Comment by anthony-tuininga** [comment]
You're welcome. All you need to do is set the fetch array size to 1000 since the default size is 100. You can do that by using the function [dpiStmt_setFetchArraySize()](https://oracle.github.io/odpi/doc/public_functions/dpiStmt.html#c.dpiStmt_setFetchArraySize). Increasing this value increases the number of of rows that are fetched in each round-trip at the expense of additional memory.

**Comment by cjbj** [comment]
> will I be able to do some steps so that it fetches first 1000 records and next 1000 records simultaneously. 

Each connection can only do 'one thing' at a time, so it isn't possible to do two concurrent fetch operations on the one connection.

**Comment by SKAHIRON** [comment]
Great! I am really thankful to you for all these valuable information. Actually I am little bit curious about the below points:
1. Once 100 row gets fetched into internal array buffer then each call to the function dpiStmt_fetchRow() advances the internal array buffer index. That means in our program we have to call this function 100 times to store the row value into our local variable. Now my question is, to avoid multiple calls to this function is there any other steps or method which can access overall 100 rows from the internal array buffer itself and make those available in the program at one go so that I can have 100 rows available in my program at one shot.

2. If point one is not possible then can I access the internal array buffer from my program directly so that I can get access to all the fetched rows at one go. 

Above two questions are really important for me. Thanks again.

**Comment by SKAHIRON** [comment]
Anthony, I am just requesting you to please give me your response on the above two questions. Thank you.

**Comment by anthony-tuininga** [comment]
Yes, if you use dpiStmt_fetch() you will have to call it 100 times. This permits you to use the dpiStmt_getQueryValue() method -- which is a bit easier to use than the other technique which I will explain to you.

First, you need to create variables for each of the columns that you are going to fetch from the database. You do this by using the method [dpiConn_newVar()](https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_newVar). If you know the types of the columns you are fetching you can use them directly, but you can also examine the metadata of the query by using the function [dpiStmt_getQueryInfo()](https://oracle.github.io/odpi/doc/functions/dpiStmt.html#c.dpiStmt_getQueryInfo). Make sure that when you create the variable you set the maxArraySize to at least the same size as the number of rows you are intending to fetch at one time. Note the last parameter which is an array of [dpiData](https://oracle.github.io/odpi/doc/structs/dpiData.html) structures. This will provide you direct access to the data as you requested.

After you have created the variables you will also need to call [dpiStmt_define()](https://oracle.github.io/odpi/doc/functions/dpiStmt.html#c.dpiStmt_define) for each of them.

Finally, you can call [dpiStmt_fetchRows()](https://oracle.github.io/odpi/doc/functions/dpiStmt.html#c.dpiStmt_fetchRows). Note that the bufferRowIndex is the index into the array of dpiData structures that were created for you when you called dpiConn_newVar(). You can then iterate through the rows by starting at bufferRowIndex and examining the next numRowsFetched rows.

Hopefully that is clear!

**Comment by cjbj** [comment]
@SKAHIRON ODPI-C provides a simpler API than Oracle Call Interface (OCI) but it is an extra layer of code, so if your app is performance sensitive you may want to use OCI instead of ODPI-C.  But don't forget that you can take a copy of ODPI-C source code and change it to do anything you want.  You can do bigger code rewrites, or simply call `dpiConn_getHandle()` if you want to compartmentalize any new code module you write.

**Comment by ddevienne** [comment]
The fact you can drop-down to raw OCI when needed is a great design decision, and one OCCI got wrong IMHO. I was told a long time ago by Oracle that handles from OCCI could not be reused with OCI, preventing such things. And at the time (years ago), OCCI lacked some OCI features (like support for XMLTYPE then). So I'm glad to read ODPI-C allows it (even though I'm using my own OCI wrappers for now). OCILIB similarly doesn't provide access to raw handles, if I recall correctly.

**Comment by vrogier** [comment]
@ddevienne OCILIB provides access to all underlying raw handles since its version 2.1 back in 2008 :) - using OCI_HandleGetXXX() calls.

**Comment by ddevienne** [comment]
Hi Vincent. I stand corrected! Sorry about that.

**Comment by SKAHIRON** [comment]
Thanks a lot Anthony and all of you. All these valuable information would really help me a lot.
One more thing I need to implement. That is, suppose I am going to fetch 1000 rows a time and want to pass this fetched rows to another process for writing to disk. Now I want this two process fetching and writing to be done simultaneously. Means 1st 1000 rows and nexr 1000 rows would be getting written simultaneously. I know I can do this using normal c++ thread. But I want to know from your end, is there any mechanism in ODPIC itself to achieve this simultaneous process.
Thanks again.

**Comment by anthony-tuininga** [comment]
ODPI-C supports threaded execution. You will have to make sure that you use the mode DPI_MODE_CREATE_THREADED in your [dpiCommonCreateParams](https://oracle.github.io/odpi/doc/structs/dpiCommonCreateParams.html#dpicommoncreateparams) structure when you create your standalone connection using [dpiConn_create()](https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_create) or session pool using [dpiPool_create()](https://oracle.github.io/odpi/doc/functions/dpiPool.html#c.dpiPool_create).

In order to have one thread reading from the database and another thread reading from the database buffers you will, however, have to use some form of synchronisation primitive, since if you call dpiStmt_fetchRows() in the one thread, it will overwrite the database buffers. But that effectively means that one thread can do all of the work anyway, since there is very little overlap. You would have to create multiple buffers to be able to manage this, and that seems fairly complex. Depending on your application there might be a better place to search for improvements!

**Comment by SKAHIRON** [comment]
Thanks a lot Anthony for your input. I will try with different connection to perform fetch operation in each connection. 
Actually why I am so interested in this because my application would be very performance sensitive. So any sort of performance optimization would be a treasure for me.

**Comment by anthony-tuininga** [comment]
Sure. I understand. I'll leave this open for a bit in case you have further questions.

**Comment by cjbj** [comment]
> my application would be very performance sensitive

@SKAHIRON You should use OCI directly.

**Comment by SKAHIRON** [comment]
@cjbj Thanks. 
=> If I use OCI instead of ODPIC, will there be much differences in performance? 
=> In OCI can I do multiple fetch operation simultaneously with one connection?

Thank you.

**Comment by SKAHIRON** [comment]
Sorry to miss one more point, OCI provides C interface and OCCI provides C++ interface.  So if I move to OCCI from ODPIC and OCI would that be more useful for me.

Thank you.

**Comment by cjbj** [comment]
> => If I use OCI instead of ODPIC, will there be much differences in performance?

You would need to benchmark, but don't forget ODPI-C is a wrapper over OCI so there is bound to be some overhead.  OCCI is also a wrapper over OCI.

> => In OCI can I do multiple fetch operation simultaneously with one connection?

No.

**Comment by anthony-tuininga** [comment]
>> => If I use OCI instead of ODPIC, will there be much differences in performance?

> You would need to benchmark, but don't forget ODPI-C is a wrapper over OCI so there is bound to be some overhead. OCCI is also a wrapper over OCI.

Yes, direct OCI is going to perform better than ODPI-C or OCCI will, all things being equal. But a few microseconds in one part of the application is unlikely to have a significant bearing on the overall performance of the application. A few microseconds inside a tight loop, however, may be significant. It is generally wise to avoid premature optimisation. You may be able to write your code in Node.js or Python (which are significantly slower than pure C) and get perfectly adequate performance. Or there may be one piece of your application that requires better performance, so you could write that part in C and hook it up to your Node.js or Python code. Without knowing the application and its needs I can't give specific advice. Hopefully what you have received here has given you enough information to make that decision! Good luck!

**Comment by SKAHIRON** [comment]
Thanks a lot! All these valuable information would really help me a lot.

In the meantime just for curiosity I was trying to implement multiple array fetch using OCCI like we did in ODPIC. Here in OCCI I have used setDataBuffer method for setting buffer for each of the fields. But the problem is once next() method of Result set gets called the buffer which I have created using setDataBuffer method, contains nothing. 
If possible would any one kindly let me know the exact steps of doing array fetch using setDataBuffer and setPreFetchRowCount methods like Anthony told me about ODPIC array fetch steps using define() and dpiStmt_fetchRows(). 

Thanks again.

**Comment by anthony-tuininga** [comment]
@SKAHIRON, based on your comments I trust that your questions have been answered -- at least the ODPI-C ones have! So I'll close this issue.

I can't help you with OCCI. You'll have to search elsewhere for help on that, I'm afraid.

**Comment by SKAHIRON** [comment]
Thanks a lot Anthony for your help !
