### ISSUE TITLE
How to access collection element via dpiObject_getElementValueByIndex() if you don't know the type in advance?

### ISSUE THREAD

**Issue by AndrSar** [oracle/odpi#75]
Hello! I want to to use **dpiObject_getElementValueByIndex()** function to fetch the dpiData from VARRAY object, but I don't know the underlying type of the element (which value of **dpiNativeTypeNum** to put in nativeTypeNum argument) in advance. This is because I write generic client code and can't make any assumptions on data types.

Is there any workaround?

**Comment by tgulacsi** [comment]
If you get an `ObjectCollection` (converting the result of an obj.Get), its `AsSlice` returns its values as slices - if possible.
Or look inside, and copy the usage of coll.First, coll.Next, coll.Get.

**Comment by tgulacsi** [comment]
Sorry, absolutely misinterpreted the question, and answered in the context of the Go driver (gopkg.in/goracle.v2) - but you can use that as an example, too: https://github.com/go-goracle/goracle/blob/master/obj.go#L129

**Comment by AndrSar** [comment]
> 
> 
> Sorry, absolutely misinterpreted the question, and answered in the context of the Go driver (gopkg.in/goracle.v2) - but you can use that as an example, too: https://github.com/go-goracle/goracle/blob/master/obj.go#L129

Thanks for the reply, but I still could not figure out the proper use of dpiObject_getElementValueByIndex() from the specified code. Also I'm not a Go programmer to study the case more deeply. From what I've learned I think that they just project the C API into more convenient Go API.

**Comment by anthony-tuininga** [comment]
If you don't know the data type information you'll have to examine the contents of the structure [dpiObjectTypeInfo](https://oracle.github.io/odpi/doc/structs/dpiObjectTypeInfo.html) and in particular the elementTypeInfo attribute which is of type [dpiDataTypeInfo](https://oracle.github.io/odpi/doc/structs/dpiDataTypeInfo.html#dpidatatypeinfo). That structure contains an attribute called defaultNativeTypeNum which you can use. In order to get to the dpiObjectTypeInfo structure you need to call the function [dpiObjectType_getInfo()](https://oracle.github.io/odpi/doc/functions/dpiObjectType.html#c.dpiObjectType_getInfo). Hopefully that should get you going!

As an aside, may I ask what you using ODPI-C for? It sounds like a driver of some sort since you mention generic client code. If that is indeed the case and you would like me to list the driver in the list mentioned on the [home page](https://oracle.github.io/odpi/), let me know!

**Comment by AndrSar** [comment]
Thank you for the quick reply! I will try and say if this works.

The project I'm working on is commercial one and closed-source, so can't say much about it except that it's in C++ and I build unified abstractions over different database drivers. By the way, your library has the cleanest interface and is most easy to use. So keep it up good work!

**Comment by anthony-tuininga** [comment]
Thanks, @AndrSar. For the kind comments as well as your description of what you are doing. :-)

**Comment by AndrSar** [comment]
I've used **dpiStmt_getQueryInfo()** to gain access first to the **dpiObjectType** (typeInfo.objectType) structure and then proceeded with **dpiObjectType_getInfo()** as stated in your answer. Everything worked as it should. So, I think, this issue can be closed. Thank you for help!

**Comment by anthony-tuininga** [comment]
You're very welcome. Glad to hear it worked as expected!
