### ISSUE TITLE
Can't set time zone information when using dpiStmt_bindValueByPos or dpiStmt_bindValueByName

### ISSUE THREAD

**Issue by felipenoris** [oracle/odpi#99]
Looks like when I bind a `dpiTimestamp` value directly to a statement using `dpiStmt_bindValueByPos` or `dpiStmt_bindValueByName`, it creates an implicit variable of oracle type `DPI_ORACLE_TYPE_TIMESTAMP`, regardless of the fact that it contains time zone information.

When executing the statement, I can see calls to `dpiVar__setValue` and it hits the code path where `oracleTypeNum == DPI_ORACLE_TYPE_TIMESTAMP`, which yields a call to 

```c
dpiDataBuffer__toOracleTimestamp(&data->value,
                        var->env, error, buffer->data.asTimestamp[pos], 0);
```

where `0` sets `withTZ`.

The main issue seems to be that `dpiStmt_bindValueByName` and `dpiStmt_bindValueByPos` don't receive the oracle type directly, but only the native type. So maybe you have to infer a oracle type for all values.

I also thought about using `dpiStmt_defineValue` to correct this problem, but the documentation says that it is intended only to fetch data.

**Comment by anthony-tuininga** [comment]
Yes, that is intended. The methods dpiStmt_bindValueByName() and dpiStmt_bindValueByPos() are intended for simple use. And unfortunately there is no way to know whether "time zone information is included" since hour and minute offsets of 0 represent a perfectly valid time zone! If you want to include time zone information you'll need to create a variable (where you can specify the Oracle type) and use dpiStmt_bindByName() or dpiStmt_bindByPos() instead.

**Comment by felipenoris** [comment]
Oh, ok. Thanks!

**Comment by felipenoris** [comment]
@anthony-tuininga Does this also applies to RAW data type? It looks like I can set its value using Variables, but not using bindValue functions.

**Comment by anthony-tuininga** [comment]
Yes, it does apply since the "native" type doesn't differentiate between strings and RAW values.
